=  Windup Maven Plugin

== Overview

Windup Maven plugin is created collaboratively on the Windup project.
This `windup-maven-plugin` repository takes the implementation of the plugin, this repository will contain the source for the official Maven plugin when the Windup 2.x ships.

== Prerequisites

To run properly, Windup maven plugin relies on Maven version 3.2.5 and later.

== Procedure to build the plugin 
    
* The first time, you must clone the windup-maven-plugin GitHub repository. 
+
----
git clone https://github.com/windup/windup-maven-plugin.git
----
    
* Navigate to the local windup-maven-plugin directory.
+
----
cd windup-maven-plugin
----

* Build the project.
+
----
mvn clean install
----

== Procedure to use the plugin

An example showing how to use the plugin can be found https://github.com/windup/windup-maven-plugin/blob/master/src/it/simple-it/pom.xml[here].

More examples will be provided as well the list of all attributes that can be used by the plugin.

NOTE: In order to run it on JDK 11, you first need to set the MAVEN_OPTS on the command line to load the *java.se* module running:
----
export MAVEN_OPTS="--add-modules=java.se"
----

NOTE: In order to run it on JDK 17, you first need to set the MAVEN_OPTS on the command line running:
----
export MAVEN_OPTS="--add-modules=java.se  --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.util.stream=ALL-UNNAMED"
----


== Procedure to release the plugin

Run the release script with required version arguments like:

----
sh build/release.sh <release.version> <development.version>
----
