name: Windup PR builder

on:
  pull_request:
    branches:
      - master
      - 'releases/**'
  push:
    branches: [ master ]

jobs:

  windup-maven-plugin-build:
    strategy:
      fail-fast: false
      matrix:
        jdk-distribution: [ temurin ]
        os: [ubuntu-latest, windows-latest, macos-latest]
        java-version: [ 11, 17 ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout windup project
        uses: actions/checkout@v3
        with:
          repository: windup/windup
          ref: ${{ github.base_ref }}
          path: windup
      - name: Checkout windup-rulesets project
        uses: actions/checkout@v3
        with:
          repository: windup/windup-rulesets
          ref: ${{ github.base_ref }}
          path: windup-rulesets
      - name: Checkout PR code
        uses: actions/checkout@v3
        with:
          path: windup-maven-plugin
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          distribution: ${{ matrix.jdk-distribution }}
          cache: 'maven'
      - name: Build Windup dependencies
        run: |
          mvn install -DskipTests -f windup
          mvn install -DskipTests -f windup-rulesets
      - name: Maven build
        run: mvn clean install -B -f windup-maven-plugin
